### ISSUE TITLE
will you please introduce howto build this java project?

### ISSUE THREAD

**Issue by catnull** [xbed/Mixly_Arduino#1]
thank  you for developing such a nice block visual style programming environment for children and the teachers who are contributing their ambitions on the Information Education. so will you please push documents that could help those who may want to personllize their project based on your jobs. thanks.

**Comment by longshine** [comment]
hi~

Thanks for your comment. This is a pure web project based on google's blockly. You may be like to view the original blockly project for instructions and docs.
Code repository: https://github.com/google/blockly
Developer site: https://developers.google.com/blockly/
